import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { WalletProvider } from '@suiet/wallet-kit';
import App from '../components/App';

export default function Home() {
  return (
    <WalletProvider>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <App />
      </div>
    </WalletProvider>
  );
}

// import { useState } from 'react';
// import { InjectedAccountWithMeta } from '@polkadot/extension-inject/types';
// import dynamic from 'next/dynamic';
// import Head from 'next/head';
// import Image from 'next/image';
// import styles from '../styles/Home.module.css';
// import { WalletProvider } from '@suiet/wallet-kit';

// const web3Accounts = dynamic(() => import('@polkadot/extension-dapp'), { ssr: false });
// const web3Enable = dynamic(() => import('@polkadot/extension-dapp'), { ssr: false });

// function App() {
//   const [account, setAccount] = useState<InjectedAccountWithMeta[]>([]);
//   const [selectedAccount, setSelectedAccount] = useState<InjectedAccountWithMeta>();

//   async function connectWallet() {
//     const { web3Enable, web3Accounts } = await import("@polkadot/extension-dapp");
//     const extensions = await web3Enable("Polki");

//     if (!extensions) {
//       throw Error("No Extension Found");
//     }

//     const allAccounts = await web3Accounts();

//     console.log(allAccounts);

//     if (allAccounts.length === 1) {
//       setSelectedAccount(allAccounts[0]);
//     }
//   }

//   return (
//     <>
//       <h2>Hey Polki, Welcome to Polkadot</h2>
//       {
//         account.length === 0 ? <button onClick={connectWallet}>Connect Wallet</button> : null
//       }
//       {
//         selectedAccount ? selectedAccount.address : null
//       }
//     </>
//   );
// }

// export default function Home() {
//   return (
//     <WalletProvider>
//       <div className={styles.container}>
//         <Head>
//           <title>Create Next App</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <App />
//       </div>
//     </WalletProvider>
//   );
// }

